spring:
  application:
    name: filenet-ms

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none